name: Build Release Packages

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
          - os: macos-latest  
            target: x86_64-apple-darwin
            name: macos-x64
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            name: linux-x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ matrix.os == 'macos-latest' && '-' || '' }}
        with:
          args: --target ${{ matrix.target }}

      - name: Package artifacts into zip
        shell: bash
        run: |
          mkdir -p packages
          cd src-tauri/target/${{ matrix.target }}/release/bundle
          
          # Create platform-specific packages
          case "${{ matrix.os }}" in
            "macos-latest")
              if [ -d "dmg" ]; then
                cd dmg && zip -r "../../../../../packages/HabitQuest-${{ matrix.name }}.zip" * && cd ..
              fi
              if [ -d "macos" ]; then
                cd macos && zip -r "../../../../../packages/HabitQuest-${{ matrix.name }}-app.zip" * && cd ..
              fi
              ;;
            "ubuntu-20.04")  
              if [ -d "appimage" ]; then
                cd appimage && zip -r "../../../../../../packages/HabitQuest-${{ matrix.name }}.zip" * && cd ..
              fi
              if [ -d "deb" ]; then
                cd deb && zip -r "../../../../../../packages/HabitQuest-${{ matrix.name }}-deb.zip" * && cd ..
              fi
              ;;
            "windows-latest")
              if [ -d "msi" ]; then
                cd msi && zip -r "../../../../../../packages/HabitQuest-${{ matrix.name }}-msi.zip" * && cd ..
              fi
              if [ -d "nsis" ]; then
                cd nsis && zip -r "../../../../../../packages/HabitQuest-${{ matrix.name }}-setup.zip" * && cd ..
              fi
              ;;
          esac

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HabitQuest-${{ matrix.name }}
          path: packages/*.zip
          retention-days: 30
