name: macOS DMG Build

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install macOS dependencies
        run: |
          # Install create-dmg for DMG creation
          npm install -g create-dmg || true

      - name: Install frontend dependencies
        run: |
          npm ci

      - name: Build frontend
        run: |
          npm run build

      - name: Build Tauri DMG (ad-hoc signing)
        uses: tauri-apps/tauri-action@v0
        env:
          APPLE_SIGNING_IDENTITY: "-"
        with:
          args: --target ${{ matrix.target }}

      - name: List build outputs
        run: |
          echo "=== Build output structure ==="
          find src-tauri/target -name "*.dmg" -o -name "*.app" -o -name "*.tar.gz" | head -20
          echo "=== Bundle directory contents ==="
          ls -la src-tauri/target/${{ matrix.target }}/release/bundle/ || echo "Bundle directory not found"
          echo "=== All target directories ==="
          ls -la src-tauri/target/ || echo "Target directory not found"
          echo "=== Release directory contents ==="
          ls -la src-tauri/target/${{ matrix.target }}/release/ || echo "Release directory not found"

      - name: Package artifacts
        run: |
          # Store the current working directory
          WORKSPACE_DIR=$(pwd)
          mkdir -p packages
          
          # Determine architecture suffix
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            ARCH="arm64"
          else
            ARCH="x64"
          fi
          
          # Create single comprehensive macOS package
          mkdir -p "temp-macos"
          
          # Copy documentation files once
          cp INSTALLATION-GUIDE.md temp-macos/
          cp README.md temp-macos/
          
          # Copy DMG file if available
          if [ -d "src-tauri/target/${{ matrix.target }}/release/bundle/dmg" ]; then
            find "src-tauri/target/${{ matrix.target }}/release/bundle/dmg" -name "*.dmg" -exec cp {} temp-macos/ \;
          fi
          
          # Copy .app bundle if available
          if [ -d "src-tauri/target/${{ matrix.target }}/release/bundle/macos" ]; then
            find "src-tauri/target/${{ matrix.target }}/release/bundle/macos" -name "*.app" -exec cp -r {} temp-macos/ \;
          fi
          
          # Create single zip package
          cd temp-macos && zip -r "../packages/HabitQuest-macos-${ARCH}.zip" * && cd "$WORKSPACE_DIR"
          
          # Clean up
          rm -rf temp-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HabitQuest-macos-${{ matrix.target }}
          path: |
            packages/*.zip
            src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          retention-days: 30