name: Windows MSI/NSIS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Install Tauri CLI
      run: |
        echo "Installing Tauri CLI via cargo..."
        cargo install tauri-cli --version ^2.0
        echo "Tauri CLI installed, checking version..."
        $env:PATH += ";$env:USERPROFILE\.cargo\bin"
        cargo tauri --version
      shell: pwsh
      
    - name: Install frontend dependencies
      run: |
        npm ci
        
    - name: Build frontend
      run: |
        npm run build
        
    - name: Build Windows installer
      run: |
        $env:PATH += ";$env:USERPROFILE\.cargo\bin"
        cargo tauri build --target ${{ matrix.target }}
      shell: pwsh
        
    - name: List build outputs
      run: |
        echo "=== Build output structure ==="
        Get-ChildItem -Recurse -Path "src-tauri/target" -Include "*.msi", "*.exe", "*.zip" -ErrorAction SilentlyContinue | Select-Object -First 20 | ForEach-Object { $_.FullName }
        echo "=== Bundle directory contents ==="
        if (Test-Path "src-tauri/target/${{ matrix.target }}/release/bundle/") {
            Get-ChildItem -Path "src-tauri/target/${{ matrix.target }}/release/bundle/" -Recurse | Format-Table Name, Length, LastWriteTime
        } else {
            echo "Bundle directory not found"
        }
        echo "=== Release directory contents ==="
        if (Test-Path "src-tauri/target/${{ matrix.target }}/release/") {
            Get-ChildItem -Path "src-tauri/target/${{ matrix.target }}/release/" | Format-Table Name, Length, LastWriteTime
        } else {
            echo "Release directory not found"
        }
      shell: pwsh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.target }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*
          src-tauri/target/${{ matrix.target }}/release/*.exe
          src-tauri/target/${{ matrix.target }}/release/*.msi
        retention-days: 30